version: '3.1'

services:
  db:
    container_name: oft-db
    image: postgis/postgis
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    labels:
      - traefik.enable=false
    volumes:
      - ${DOCKER_VOL}/postgres:/var/lib/postgresql/data